### ISSUE TITLE
Additional madrid_flags

### ISSUE THREAD

**Issue by mbrennan-afa** [toffer/iphone-sms-backup#3]
Now sure how these particular flags should work but I noticed they don't appear in the convert_address_imessage() which causes the script to break.

102405 
77825

Hope that helps :)

**Comment by toffer** [comment]
Can you tell me what the value of `madrid_handle` is for the messages where `madrid_flags` is "102405" or "77825"?  

Or, better yet, can you dump the whole row in `message` for those examples?

**Comment by mbrennan-afa** [comment]
No problemo.

<pre>
(330, 342944799, None, u'[addressed removed]@gmail.com', 0, 0, u'+[phone number removed]', 102405, 0, 1, 0, 342944802)

(847, 346150528, None, u'[phone number removed] dave', 0, 0, u'+[phone number removed]', 77825, 0, 1, 346155183, 0)
</pre>


If you need anything else let me know.
Thanks
